import Head from 'next/head'
import Image from 'next/image'
import { Jura } from '@next/font/google'

const jura = Jura({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'], 
  variable: '--font-jura' })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"w-full bg-regal-black h-screen"}>
        <header className='flex pl-5 pr-5 pt-10 justify-around'>
          <h1 className={`${jura.variable} font-sans text-r-white text-lg lg:text-4xl`}>SATURN</h1>
          <div className='flex w-2/4 justify-center space-x-10'>
            <a className={`${jura.variable} font-sans text-r-white/75 hover:text-r-white lg:text-2xl`}>Home</a>
            <a className={`${jura.variable} font-sans text-r-white/75 hover:text-r-white lg:text-2xl`}>Rockets</a>
          </div>
          <button className='border-solid border-2 border-r-white/75 rounded-2xl text-r-white/75 hover:text-r-white hover:border-r-white lg:text-2xl'>
            <a className={`${jura.variable} font-sans py-10 px-5 lg:py-20`}>Review Rockets</a>
          </button>      
        </header>
        <div>

        </div>
      </main>
    </>
  )
}
